### ISSUE TITLE
small syntax error in (at least) one of the run.sh files

### ISSUE THREAD

**Issue by Aliebaba99** [janneshopman/RKSymFoam#7]
bash-4.4$ ./run.sh RKSymFoam laminar
Running with RKSymFoam
./run.sh: line 43: syntax error in conditional expression: unexpected token `;'
./run.sh: line 43: syntax error near `;'
./run.sh: line 43: `    if [[ $RKSCHEME != "BackwardEuler" && $RKSCHEME != "Kutta"]]; then'

space missing after the second conditional
this was in the cases/channel180/templateCase

**Comment by janneshopman** [comment]
thanks, updated and commited
